name: spacex_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    


  
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  animated_text_kit: ^4.2.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - assets/fonts/

  fonts:
    - family: Space Mono
      fonts:
        - asset: assets/fonts/SpaceMono-Italic.ttf
    

